import pathlib

out = pathlib.Path(r"D:/AIM-Contract/e-commerce-ai/public/try-on.html")

lines = [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="UTF-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    "  <title>AR Goggles Try-On</title>",
    '  <script src="https://aframe.io/releases/1.4.2/aframe.min.js"></script>',
    '  <script src="https://cdn.jsdelivr.net/npm/mind-ar@1.2.5/dist/mindar-face-aframe.prod.js"></script>',
    "  <style>",
    "    *{margin:0;padding:0;box-sizing:border-box}",
    "    html,body{width:100%;height:100%;overflow:hidden;background:#000;font-family:-apple-system,sans-serif}",
    "    #topbar{position:fixed;top:0;left:0;right:0;z-index:9999;display:flex;align-items:center;justify-content:space-between;padding:10px 16px;background:linear-gradient(180deg,rgba(0,0,0,.65) 0%,transparent 100%);pointer-events:none}",
    "    .logo{display:flex;align-items:center;gap:8px}",
    "    .logo-icon{background:#2874f0;color:#fff;width:36px;height:36px;border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:18px}",
    "    .logo-text{color:#fff;font-weight:800;font-size:18px}",
    "    .logo-sub{color:#ffc200;font-size:10px;font-weight:700;display:block;margin-top:-2px}",
    "    #close-btn{pointer-events:all;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.3);color:#fff;width:38px;height:38px;border-radius:50%;cursor:pointer;font-size:20px;display:flex;align-items:center;justify-content:center;backdrop-filter:blur(6px);text-decoration:none;transition:background .2s}",
    "    #hint{position:fixed;bottom:24px;left:50%;transform:translateX(-50%);z-index:9999;background:rgba(0,0,0,.55);backdrop-filter:blur(8px);color:#fff;font-size:13px;padding:10px 22px;border-radius:50px;border:1px solid rgba(255,255,255,.18);white-space:nowrap;pointer-events:none}",
    "    #loading-overlay{position:fixed;inset:0;z-index:10000;background:#0b0b12;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:20px;transition:opacity .5s}",
    "    #loading-overlay.hidden{opacity:0;pointer-events:none}",
    "    .spinner{width:52px;height:52px;border:4px solid rgba(255,255,255,.1);border-top-color:#2874f0;border-radius:50%;animation:spin .85s linear infinite}",
    "    @keyframes spin{to{transform:rotate(360deg)}}",
    "    #loading-overlay p{color:rgba(255,255,255,.7);font-size:14px;text-align:center}",
    "    #error-overlay{position:fixed;inset:0;z-index:10001;background:#0b0b12;display:none;flex-direction:column;align-items:center;justify-content:center;gap:16px;padding:24px;text-align:center}",
    "    #error-overlay h2{color:#fff;font-size:20px;font-weight:700}",
    "    #error-overlay p{color:rgba(255,255,255,.55);font-size:14px;max-width:320px}",
    "    #error-overlay a{margin-top:8px;background:#2874f0;color:#fff;padding:12px 28px;border-radius:50px;font-weight:700;text-decoration:none;font-size:14px}",
    "  </style>",
    "</head>",
    "<body>",
    "",
    '  <div id="loading-overlay"><div class="spinner"></div><p>Starting camera &amp; face tracking&#8230;</p></div>',
    "",
    '  <div id="error-overlay">',
    '    <div style="font-size:52px">&#128247;</div>',
    "    <h2>Camera Access Required</h2>",
    "    <p>Allow camera access in your browser then reload to use AR try-on.</p>",
    '    <a href="javascript:location.reload()">Reload &amp; Allow</a>',
    "  </div>",
    "",
    '  <div id="topbar">',
    '    <div class="logo">',
    '      <div class="logo-icon">&#9889;</div>',
    "      <div>",
    '        <span class="logo-text">SmartShop</span>',
    '        <span class="logo-sub">AR Try-On</span>',
    "      </div>",
    "    </div>",
    '    <a id="close-btn" href="javascript:history.back()" title="Close">&#x2715;</a>',
    "  </div>",
    "",
    "  <a-scene",
    '    id="ar-scene"',
    '    mindar-face="autoStart: true;"',
    '    color-space="sRGB"',
    '    renderer="colorManagement: true, physicallyCorrectLights"',
    '    vr-mode-ui="enabled: false"',
    '    device-orientation-permission-ui="enabled: false"',
    "  >",
    "    <a-assets>",
    '      <a-asset-item id="gogglesModel" src="/api/models/aviation_goggles_revised.glb"></a-asset-item>',
    "    </a-assets>",
    "    <a-camera active=\"false\"></a-camera>",
    '    <a-entity mindar-face-target="anchorIndex: 168">',
    '      <a-gltf-model src="#gogglesModel" position="0 0.04 0.07" scale="1.6 1.6 1.6" rotation="0 0 0"></a-gltf-model>',
    "    </a-entity>",
    "  </a-scene>",
    "",
    '  <div id="hint">&#128083; Look straight into the camera to try on the goggles</div>',
    "",
    "  <scr" + "ipt>",
    '    var L=document.getElementById("loading-overlay");',
    '    var E=document.getElementById("error-overlay");',
    '    var S=document.getElementById("ar-scene");',
    '    S.addEventListener("arReady",function(){L.classList.add("hidden");});',
    '    S.addEventListener("arError",function(){L.classList.add("hidden");E.style.display="flex";});',
    "    setTimeout(function(){L.classList.add(\"hidden\");},15000);",
    "  </scr" + "ipt>",
    "",
    "</body>",
    "</html>",
]

content = "\n".join(lines)
out.write_text(content, encoding="utf-8")
print(f"Written: {len(lines)} lines to {out}")
